<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_checkoutBtn</name>
   <tag></tag>
   <elementGuidId>039f9782-8797-4315-810a-7a5236b84be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkoutBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'checkoutBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>626982f2-8201-440a-9807-0022015e740f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>checkout.php</value>
      <webElementGuid>fb2fc7a9-0289-4ba3-b204-ecba34362b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkoutBtn</value>
      <webElementGuid>fe62c6f2-fcc3-4f2b-a6ad-d3a1e516a462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-primary font-weight-bold my-3 py-3</value>
      <webElementGuid>8e906043-9525-4519-8501-b2ea22c08f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed To Checkout</value>
      <webElementGuid>8d8657eb-ee8d-43aa-be04-f24cef965086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c4ff22d8fb95463a2ad86f7726221d78</value>
      <webElementGuid>0aa82031-c090-4e9a-8598-40023db1fe94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'checkoutBtn']</value>
      <webElementGuid>38e23c13-57f4-4c2e-a5d5-1b66055c4993</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'checkoutBtn']</value>
      <webElementGuid>00866f4f-d42f-4893-82d2-43e5a4b9993a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'checkout.php' and @id = 'checkoutBtn' and (text() = 'Proceed To Checkout' or . = 'Proceed To Checkout')]</value>
      <webElementGuid>3c55b734-8891-4fcd-920d-d453994e6654</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
