<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop</name>
   <tag></tag>
   <elementGuidId>5d886800-4a85-45b6-8cd6-03d0e8e1d399</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.breadcrumb-item[href=&quot;shop\.php&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' breadcrumb-item ') and (@href = 'shop.php')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bff40c84-825a-4f88-a966-3ecaaa8796ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb-item text-dark</value>
      <webElementGuid>89cadb0d-8eee-403f-bdef-6dbbc6688aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>shop.php</value>
      <webElementGuid>10c4a0e9-d992-4878-aefb-f2bddbe6818d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>1e6b5f28-9bb2-4ed8-b6df-77bb913fc470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0d41146db017072dfb18d65a7b036809</value>
      <webElementGuid>14e9bd87-5fb2-436e-9198-021818dac3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' breadcrumb-item ') and (@href = 'shop.php')]</value>
      <webElementGuid>ea52a64b-4be9-4a22-856e-e8b2d2fb6bc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' breadcrumb-item ') and (@href = 'shop.php')]</value>
      <webElementGuid>2a1f4e60-9803-4790-8afc-d3bd8c71d0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'shop.php' and (text() = 'Shop' or . = 'Shop')]</value>
      <webElementGuid>7c5193cb-6205-4dad-8271-31149742a08d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
