<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_loginBtn</name>
   <tag></tag>
   <elementGuidId>6286a7c3-1660-4000-9455-e88f931e4d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'loginBtn selfhealing']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5e42b7f-965f-4117-a0ec-46abc1c05588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginBtn</value>
      <webElementGuid>0b32c596-c4dc-4bdf-adf3-c4c75390e30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary py-2 px-4</value>
      <webElementGuid>8aeabde5-1577-4fc1-bc70-2f0c5a33601e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>4f333c16-11da-49df-91c5-83a94015dd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1c6d9aff2df761263417d19db21167b2</value>
      <webElementGuid>302551aa-326d-4218-911e-fe1c8f2d0317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'loginBtn']</value>
      <webElementGuid>019c28ae-a6fc-441d-8788-0faf6f4e5b10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'loginBtn']</value>
      <webElementGuid>5680bfda-8e2b-482a-a2d2-5533cd6743de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'loginBtn' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>35512d23-2247-4328-af43-262af3db4fb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
