<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter State</name>
   <tag></tag>
   <elementGuidId>a283836d-7ac9-469b-9961-162d76ead94b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#states</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'states']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17ec5943-8551-4888-81ad-b7e03326aabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d1e80dcf-0c7f-4660-8695-c0e130e93e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1fd6c74d-5fb6-4ea9-9527-4ea67ad7fd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>16ff95fa-ec60-4cec-9d7a-4c33c6daef4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter State</value>
      <webElementGuid>593c79fc-0815-4a04-a975-99f6d72c3088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e0aa3d2f8c43cee987a1af5683bdfb5c</value>
      <webElementGuid>e6f7b393-ea32-41c2-af5f-dbadd1d4ddcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'states']</value>
      <webElementGuid>510443b0-a52c-4dd5-b9e1-4fea08747607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'states']</value>
      <webElementGuid>9c058223-4401-41ca-a26a-cdcf3cf5138e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'states' and @placeholder = 'Enter State']</value>
      <webElementGuid>d13889d6-bcfa-4222-ae59-e60dc5a04ce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
