<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Pin Code</name>
   <tag></tag>
   <elementGuidId>5d30da98-655d-4714-a9bd-b4e25417e740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pincode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'pincode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51c5bcfd-f2d9-45e6-a650-154a6c558b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c2313d56-e202-4ff6-bc00-2dd19fa2c6a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>355a7db9-d4e7-41ee-918c-2cfc80c02e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a36553a5-cbbb-40df-a94a-0089a7d39e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pincode</value>
      <webElementGuid>23baa693-7e8e-47b8-98f7-ed21cadbcbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Pin Code</value>
      <webElementGuid>cd4c6931-e552-4d3b-a128-25790924eeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-94646f40256b9f3b6c082646b1d3ff01</value>
      <webElementGuid>59e9aa98-fd18-4d45-954a-e817dd80e08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'pincode']</value>
      <webElementGuid>3a2295a1-1ab9-43b1-adae-7123eaacccd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'pincode']</value>
      <webElementGuid>a67d12a4-704d-4b83-b2f5-f591d9b9e2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'pincode' and @placeholder = 'Enter Pin Code']</value>
      <webElementGuid>41711406-302e-4b89-93e5-237b066b0288</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
