<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Middle Name</name>
   <tag></tag>
   <elementGuidId>578c8826-4684-4d87-9b06-daf01f0964c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#middlename</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'middlename']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>656a7192-e871-43bb-a3d8-d2078562d0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>72abd63c-72c4-4d25-9c3a-32e7d53e3d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>middlename</value>
      <webElementGuid>507b7aa6-dc8a-40a0-9b34-885f319c2375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>974c1580-2fe5-4fd6-8985-da6937305f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Middle Name</value>
      <webElementGuid>df2088c9-962e-439a-a300-8b4f982f5cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-aa092847ccc2d34c4e68b00e1b2858db</value>
      <webElementGuid>66864f9e-8eb4-4d0c-9fd1-58dfe29d08c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'middlename']</value>
      <webElementGuid>f6035629-2a7c-451e-9194-f153ec56602e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'middlename']</value>
      <webElementGuid>047cecfa-f222-4a64-9057-67e979ae67e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'middlename' and @type = 'text' and @placeholder = 'Enter Middle Name']</value>
      <webElementGuid>77524f42-8fb0-4a7c-8c04-d55a2d8b1a72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
