<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop</name>
   <tag></tag>
   <elementGuidId>57cef61a-687e-4e69-8b4a-bdd996e8bf7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.header-menu-container [href=&quot;https\:\/\/shop\.qaautomationlabs\.com\/&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' header-menu-container ')]//*[@href = 'https://shop.qaautomationlabs.com/']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50cf6501-0485-4361-a981-e9164c1b0e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://shop.qaautomationlabs.com/</value>
      <webElementGuid>569e8d5d-358c-49d0-98de-b170111461fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>4986602b-082c-48be-841e-2eab4bb71448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-dc355687316c7eaf04e36efcff3b0844</value>
      <webElementGuid>55adcd65-b6ae-4334-b693-85893522ae8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' header-menu-container ')]//*[@href = 'https://shop.qaautomationlabs.com/']</value>
      <webElementGuid>c3478731-5001-4fec-b5bb-745c65f9fbac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' header-menu-container ')]//*[@href = 'https://shop.qaautomationlabs.com/']</value>
      <webElementGuid>5a445cde-be7a-47e9-88c9-fcee74ed4743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://shop.qaautomationlabs.com/' and (text() = 'Shop' or . = 'Shop')]</value>
      <webElementGuid>ae8ff883-2c30-4099-ae88-ddb0092cf623</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
