<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shop</name>
   <tag></tag>
   <elementGuidId>ad81cd36-9fca-437c-bd3b-1cdea01a7975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.header-menu-container [href=&quot;https\:\/\/shop\.qaautomationlabs\.com\/&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' header-menu-container ')]//*[@href = 'https://shop.qaautomationlabs.com/']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://shop.qaautomationlabs.com/' and (text() = 'Shop' or . = 'Shop')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01eb5ae5-16f0-4af3-860e-584d61945d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://shop.qaautomationlabs.com/</value>
      <webElementGuid>4c47ddee-3a63-4371-b3ea-067d337fde8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop</value>
      <webElementGuid>b3c1c6c8-e36a-4e8e-ab61-78b83f69e710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-dc355687316c7eaf04e36efcff3b0844</value>
      <webElementGuid>4d2d99bd-a2f6-4f4c-88ed-5b934dd40582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' header-menu-container ')]//*[@href = 'https://shop.qaautomationlabs.com/']</value>
      <webElementGuid>29d777b1-6169-429d-90b8-74367006c99f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' header-menu-container ')]//*[@href = 'https://shop.qaautomationlabs.com/']</value>
      <webElementGuid>79926659-7183-442b-8e3f-95ca2a99f726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://shop.qaautomationlabs.com/' and (text() = 'Shop' or . = 'Shop')]</value>
      <webElementGuid>199c1fcc-b812-4bf9-8196-cb8f18da56f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
