<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter State</name>
   <tag></tag>
   <elementGuidId>daa26f83-7236-4796-9bdf-372a33162591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#states</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'states']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9917018-44e5-4356-8d3c-dad583b788c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c63904fc-19ad-4a4f-a139-e751d3673191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49875566-bd3d-46e5-9cda-3bb7de15effe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>51021fab-cca4-4790-ad52-35cd036e0bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter State</value>
      <webElementGuid>f0fba385-eee9-4e0b-acf0-26793bf35c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e0aa3d2f8c43cee987a1af5683bdfb5c</value>
      <webElementGuid>45995896-f583-4eaf-a643-6dbc1c5bb3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'states']</value>
      <webElementGuid>aa6a79e3-34a8-4d72-8f64-ce68f3940c84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'states']</value>
      <webElementGuid>7e9765fe-804f-4e36-bb80-a8721955641f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'states' and @placeholder = 'Enter State']</value>
      <webElementGuid>8aa1bdae-2c68-460b-ad9f-98200380a058</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
