<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Pin Code</name>
   <tag></tag>
   <elementGuidId>68223b5c-f2c9-4b3a-a3a1-0588bba3a1e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pincode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'pincode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5d907f3-5bc0-4423-b2f4-628bbf02e40e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4ba3f7ff-726f-42e7-8d2b-ed1e75dc0b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a0525355-5e9a-4c9d-99b8-fcd9a833d9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>570793d0-672a-4d4a-9dc5-b9676a72ac07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pincode</value>
      <webElementGuid>faeec947-a125-44fb-aa60-a197e5014a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Pin Code</value>
      <webElementGuid>c29b496f-143c-473e-bfe3-325299c8a335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-94646f40256b9f3b6c082646b1d3ff01</value>
      <webElementGuid>21bd9a41-f042-4371-8198-aa34acc4acdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'pincode']</value>
      <webElementGuid>83a2550a-e664-4542-a650-48ddb57bc9cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'pincode']</value>
      <webElementGuid>d82108bc-1ecc-4e07-972b-4a583a7e4184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'pincode' and @placeholder = 'Enter Pin Code']</value>
      <webElementGuid>08694b44-f1cd-4eee-8965-a8216125d287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
